### ISSUE TITLE
running the tutorial with java

### ISSUE THREAD

**Issue by CruncherBigData** [Cascading/scalding-tutorial#2]
Is it all possible that I can run the tutorials using java instead of Hadoop? Ie. 
java -jar target/scalding-tutorial-0.8.5.jar <TutorialPart> --local <addtional arguments>

thanks.

**Comment by fs111** [comment]
No, the build is producing a hadoop specific jar and not a normal jar, which can just be passed to java. There is however no need for a hadoop cluster, just grab hadoop from apache, untar it and put it in your path. That's all, that is needed to run the tutorial.

**Comment by CruncherBigData** [comment]
good point I will try to just download hadoop. 
thanks.

**Comment by fs111** [comment]
I have added a small section to the README to clarify this a bit. Thanks for giving me this idea.
